### ISSUE TITLE
FILE error, Deluge unable to read files

### ISSUE THREAD

**Issue by turbo** [jamiefaye/downrush#1]
Hi there, 

First off, thanks for your amazing contribution to the Deluge community. Now onto my problem:

I have a W-04 64GB SD card and completed the install guide as presented in the README. This is my status:

1. The deluge can't read any file from the card
2. With the deluge powered on, I can connect to the card and browse all files (synths, kits etc) and view my song XMLs - albeit very, very slowly

I'm on the 1.4 firmware on the deluge.

**Comment by turbo** [comment]
Nevermind, I needed to change the partition from exfat to fat32 :)

**Comment by jamiefaye** [comment]
Thanks for letting me know how you resolved this. I have a 64GB FlashAir I was wondering what to do with!
